module_order:
    - fastqc:
        name: 'FastQC Raw'
        anchor: 'fastqc_raw'
        path_filters:
            - '*R[12]_001_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC Trimmed'
        anchor: 'fastqc_trimmed'
        path_filters:
            - '*_val_1_fastqc.zip'
            - '*_val_2_fastqc.zip'
            - '*_ribotrim_R[12]_fastqc.zip'
    - hisat2
    - htseq
    - rseqc:
        path_filters:
            - '*/RSeQC_Results/Main_All_Genes*'
fn_ignore_files:
    - '*Ribo*'
    - 'slurm*out'
extra_fn_clean_exts:
    - '_AlignStat.txt'
    - '_rf_GeneCount.txt'
    - '_GeneCount.txt'
    - '_ribotrim_R1'
    - type: regex
      pattern: '_val_[12]'
    - type: regex
      pattern: '_L[0-9]{3}_R[12]_[0-9]{3}'
    - type: regex
      pattern: 'Main_All_Genes_'
    - type: regex
      pattern: '_bam_stats'